name: Automatic tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test_install_swivm:
    name: Install swivm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install swivm
        uses: ./actions/install@test-v5-via-github-actions

      - name: Print swivm version
        run: |
          source ~/.swivm/swivm.sh
          swivm --version

  test_load_swipl:
    name: Install swivm and load SWI-Prolog version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swipl: ["stable", "devel", "8", "7", "6", "5"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install swivm and load SWI-Prolog
        uses: ./actions/load@test-v5-via-github-actions
        with:
          swi-prolog-version: ${{ matrix.swipl }}

      - name: Print SWI-Prolog version
        run: |
          source ~/.swivm/swivm.sh
          swipl --version
